title: Cheng (Jonathan) Wang
author:
  name: Cheng Wang
  email: "cw997@cornell.edu"
logo: /assets/profile_circle.png
description: >
  Project portfolio of Cheng (Jonathan Wang).
plugins:
  - jekyll-feed
  - jekyll-seo-tag

theme: minima
social_links:
   - { platform: github,         user_url: "https://github.com/jekyll/minima" }
  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/cheng-wang-1a5465219/" }
