title: Cheng Wang
description: Current Master's student in Information Science at Cornell university with experience in data analysis, academic research, business consulting and brand consulting.
logo: /assets/profile_circle.png
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
github: false
