title: Cheng Wang
description: Current Master's student in Information Science at Cornell university with experience in data analysis, academic research, business consulting and brand consulting.
logo: /assets/profile_circle.png
theme: jekyll-theme-minimal
github: false
